# 01 - NumPy

In [1]:
import numpy as np
import pandas as pd
import os
import sys
from IPython.display import display

print("="*15+" NUMPY VERSIÓN")
print("Instrucción en un print: np.__version__")
print(np.__version__) # imprime versión de numpy (sólo números)

=============== NUMPY VERSIÓN
Instrucción en un print: np.__version__
2.4.1


# 1.1 ARRAYS: MÉTODO Y PROPIEDADES

### 1.1.1 *Método* **.array()** 

`np.array(lista)`: 
- Crea un array a partir de la lista o tupla.
- El array creado es del tipo **ndarray**
- Los elementos de la lista o tupla han de ser TODOS DEL MISMO TIPO
- La función devuelve una referencia a él.


### 1.1.2 Dimensiones de un array
- El número de dimensiones de un array dependerá de las listas o tuplas anidadas en lista que se convierte.
    * **VECTOR**: Para una lista de valores se crea un array de una dimensión.
    * **MATRIZ**: Para una lista de listas de valores se crea un array de dos dimensiones.

`np.array(lista, otros parámetros como ndmin=número máximo de columnas)`


### 1.1.3 PROPIEDADES de un array
**ndim** = numero de dimensiones  
**dtype** = tipo de datos a lo que ha convertido numpy el array *(Strings: U8 Unicode con la longitud del más largo)*  
**shape** = devuelve una tupla con las (filas, columnas) del array

In [2]:
# CÓDIGO DE LA SECCIÓN 1.1 ARRAYS: MÉTODO Y PROPIEDADES

# 1.1.1 MÉTODO .ARRAY()
print("="*15+" 1.1.1 MÉTODO ARRAY()")
lista = [1,2,4,34,4,32,2]
tupla = (1,2,4,34,4,32,2)

# Crear un array a partir de la lista

print("Array de la lista")
array_de_lista = np.array(lista) # Método array() crea un ndarray
print(array_de_lista) # [ 1  2  4 34  4 32  2]
print(type(array_de_lista)) #ndarray 

array_de_tupla = np.array(tupla)
print("Array de la tupla")
print(array_de_tupla) # [ 1  2  4 34  4 32  2]
print(type(array_de_tupla)) #ndarray

# 1.1.2 DIMENSIONES de un array
print(f'\n{"="*15} 1.1.2 DIMENSIONES: VECTOR Y MATRIZ')
# A) VECTOR: 1 dimensión
vector = np.array([1,2,3,4,5])
print(f'A) Vector o array unidimensional: {vector}') # Array unidimensional: [1 2 3 4 5]

# B) MATRIZ: 2 dimensiones
matriz = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f'B) Matriz o array bidimensional (matriz):\n{matriz}')
#[[1 2 3]
#[4 5 6]
#[7 8 9]]


# 1.1.3 PROPIEDADES de un array
print(f'\n{"="*15} 1.1.3 PROPIEDADES de un array')
# A) PROPIEDAD NDIM
print(f'A) PROPIEDAD NDIM')
print(f'Numero de dimensiones del array de la lista: {array_de_lista.ndim}') # Número de dimensiones: 1
print(f'Número de dimensiones del vector: {vector.ndim}') # Número de dimensiones: 1
print(f'Número de dimensiones de la matriz: {matriz.ndim}') # Número de dimensiones: 2

# B) PROPIEDAD SHAPE
print(f'\nB) PROPIEDAD SHAPE')
print(f'Shape del array_de_lista: {array_de_lista.shape}') # Shape del array: (7,)
# 7 elementos, sin una estructura de filas/columnas
print("array_de_lista: 7 elementos, sin una estructura de filas/columnas")
print(f'Shape del vector: {vector.shape}') # Shape del vector: (5,)
print("Vector: 5 elementos, sin una estructura de filas/columnas")
print(f'Shape de la matriz: {matriz.shape}') # Shape de la matriz: (3, 3)
print("matriz: 3 filas y 3 columnas (FILAS, COLUMNAS)")

# C) PROPIEDAD DTYPE
#dtype = tipo de datos tal como los ha convertido NumPy dentro del array U8 Unicode con la longitud del más largo
print(f'\nC) PROPIEDAD DTYPE')
array_con_strings = np.array(["Pepe","Luis","Ana","Federico","María"])
print(f'Dtype del array_con_strings: {array_con_strings.dtype}') # Dtype del array_con_strings: <U8  (U8 = Unicode con longitud máxima 8)
# Los arrays deben ser HOMOGÉNEOS, es decir, todos los elementos del array deben ser del mismo tipo de dato
# Si se mezclan tipos de datos, NumPy convierte todos los elementos al tipo de dato que pueda contener a todos los elementos
array_mezclado_strings = np.array([["Pepe","Luis","Ana","Federico","María"],[1,2,3,4,5]],ndmin=2)
print(f'Shape del array_mezclado_strings: {array_mezclado_strings.shape}') #(2,5)
#TODAS LAS COLUMNAS TIENEN QUE TENER EL MISMO NÚMERO DE ELEMENTOS, SI NO, PON '' EN LAS QUE FALTEN
print(f'Dtype del array_mezclado_strings: {array_mezclado_strings.dtype}') # Dtype del array_mezclado_strings: <U21 





=============== 1.1.1 MÉTODO ARRAY()
Array de la lista
[ 1  2  4 34  4 32  2]
<class 'numpy.ndarray'>
Array de la tupla
[ 1  2  4 34  4 32  2]
<class 'numpy.ndarray'>

=============== 1.1.2 DIMENSIONES: VECTOR Y MATRIZ
A) Vector o array unidimensional: [1 2 3 4 5]
B) Matriz o array bidimensional (matriz):
[[1 2 3]
 [4 5 6]
 [7 8 9]]

=============== 1.1.3 PROPIEDADES de un array
A) PROPIEDAD NDIM
Numero de dimensiones del array de la lista: 1
Número de dimensiones del vector: 1
Número de dimensiones de la matriz: 2

B) PROPIEDAD SHAPE
Shape del array_de_lista: (7,)
array_de_lista: 7 elementos, sin una estructura de filas/columnas
Shape del vector: (5,)
Vector: 5 elementos, sin una estructura de filas/columnas
Shape de la matriz: (3, 3)
matriz: 3 filas y 3 columnas (FILAS, COLUMNAS)

C) PROPIEDAD DTYPE
Dtype del array_con_strings: <U8
Shape del array_mezclado_strings: (2, 5)
Dtype del array_mezclado_strings: <U21


# 1.2 **INTERPRETACIÓN DE LAS DIMENSIONES (sobre todo a partir de la 3º dimensión)**

- El número de dimensiones de un array dependerá de las listas o tuplas anidadas en lista que se convierte.
    * **VECTOR**: Para una lista de valores se crea un array de una dimensión.
    * **MATRIZ**: Para una lista de listas de valores se crea un array de dos dimensiones.

`np.array(lista, otros parámetros como ndmin=número máximo de columnas)`


`np.array([[2],[2]],ndmin=3) *ndim=3 añade la tercera dimensión*`


# 1.2.1 ARRAY SIN EL PARÁMETRO ndim=3**
El contenido sería:
[[2],
 [2]]

*Interpretación:* es un array 2D con forma (2, 1)
    2 filas
    1 columna

# 1.2.2 ARRAY con EL PARÁMETRO ndim=3** 
ndmin=3 NO añade datos, añade EJES de tamaño 1 por delante hasta llegar a **3 DIMENSIONES**.

### **A) - Primer ejemplo**
```
    [[[2]
[2]]]
```
No son filas ni columnas, **son EJES**. *“el array tiene 3 ejes, y en cada eje hay cierto número de elementos”*
**SHAPE = (1,2,1)**  
Axis--------Tamaño  
axis 0------1  [primer eje] --> en este eje hay 1 elemento que es el número [-----[[2][2]]-----]  
axis 1------2  [segundo eje] --> en este eje hay 2 elementos que son los números 2 y 2 [-----[2][2]-----]  
axis 2------1 [tercer eje]-- > en este eje hay 1 elemento que es el número 2 [2]  

### **B) - Segundo ejemplo**
```
    [[[2,2]
[2,2]]]
```

**REPETIMOS:** No son filas ni columnas, **son EJES**. *“el array tiene 3 ejes, y en cada eje hay cierto número de elementos”*  
**SHAPE = (1,2,2)**  
Axis--------Tamaño  
axis 0------1  [primer eje] --> en este eje hay 1 elemento que es el número [-----[[2,2][2,2]]-----]  
axis 1------2  [segundo eje] --> en este eje hay 2 elementos que son los números 2 y 2 [-----[2,2][2,2]-----]  
axis 2------1 [tercer eje]-- > en este eje hay 2 elementos que son el número 2 [2,2]  

In [3]:
# CÓDIGO DE LA SECCIÓN 1.2 INTERPRETACIÓN DE LAS DIMENSIONES (sobre todo a partir de la 3º dimensión)
#ndmin = número mínimo de dimensiones que tendrá el array creado
print(f'\n{"="*15} 1.2 INTERPRETACIÓN DE LAS DIMENSIONES (sobre todo a partir de la 3º dimensión)')

array_de_3_dimensiones_a = np.array([[2],[2]],ndmin=3)
print(f'\nA) Primer ejemplo primero: Array con 3 dimensiones a: {array_de_3_dimensiones_a}') 
# [[[2]
#  [2]]]

print(f'Shape del array_de_3_dimensiones_a: {array_de_3_dimensiones_a.shape}') #(1,2,1)
#No son filas ni columnas, **son EJES**. *“el array tiene 3 ejes, y en cada eje hay cierto número de elementos”*  
#Axis--------Tamaño  
#axis 0------1  [primer eje] --> en este eje hay 1 elemento que es el número [-----[[2][2]]-----]
#axis 1------2  [segundo eje] --> en este eje hay 2 elementos que son los números 2 y 2 [-----[2][2]-----]
#axis 2------1 [tercer eje]-- > en este eje hay 1 elemento que es el número 2 [2]

print("\nB) Segundo ejemplo: el array anterior con 3 dimensiones pero con más elementos")
array_de_3_dimensiones_b = np.array([[2,2],[2,2]],ndmin=3)
print(f'\nArray con 3 dimensiones b: {array_de_3_dimensiones_b}') 
# [[[2,2]
#  [2,2]]]

print(f'Shape del array_de_3_dimensiones_b: {array_de_3_dimensiones_b.shape}') #(1,2,2)
#No son filas ni columnas, **son EJES**. *“el array tiene 3 ejes, y en cada eje hay cierto número de elementos”*  
#Axis--------Tamaño  
#axis 0------1  [primer eje] --> en este eje hay 1 elemento que es el número [-----[[2,2][2,2]]-----]
#axis 1------2  [segundo eje] --> en este eje hay 2 elementos que son los números 2 y 2 [-----[2,2][2,2]-----]
#axis 2------1 [tercer eje]-- > en este eje hay 2 elementos que son el número 2 [2,2]

# OTRO EJEMPLO: un arrayGigante con 10 dimensiones
arrayGigante = np.array([1,2,3],ndmin=10)
print("\nC) Un Array Gigante con 10 dimensiones:")
print(arrayGigante) # [[[[[[[[[[1 2 3]]]]]]]]]]
print(f'SHAPE del arrayGigante: {arrayGigante.shape}') # (1, 1, 1, 1, 1, 1, 1, 1, 1, 3)


=============== 1.2 INTERPRETACIÓN DE LAS DIMENSIONES (sobre todo a partir de la 3º dimensión)

A) Primer ejemplo primero: Array con 3 dimensiones a: [[[2]
  [2]]]
Shape del array_de_3_dimensiones_a: (1, 2, 1)

B) Segundo ejemplo: el array anterior con 3 dimensiones pero con más elementos

Array con 3 dimensiones b: [[[2 2]
  [2 2]]]
Shape del array_de_3_dimensiones_b: (1, 2, 2)

C) Un Array Gigante con 10 dimensiones:
[[[[[[[[[[1 2 3]]]]]]]]]]
SHAPE del arrayGigante: (1, 1, 1, 1, 1, 1, 1, 1, 1, 3)


# 1.3 ÍNDICES de los Arrays

### 1.3.1 Array 2 dimensiones

`array_2d_otro = np.array([[1,2,3,4,5], [6,7,8,9,10]])`

```
print(f'{array_2D[1][3],array_2D[0][3]}')# 9 y # 4 
print(array_2D[1,4]) # 10 primer numero es el array, segundo la posición
print(f'{array_2D[1][3] + array_2D[0][3]}') # SUMA y sale 13
print(f'{type(array_2D[1][3]),array_2D[0][3]}') #Type da (<class 'numpy.int64'>, np.int64(4))
```

### 1.3.2 Array 3 dimensiones
`array_3D = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])`

```
print(array_3D[0]) #[[1 2 3]
                #[4 5 6]]
print(array_3D[0][0]) #[1 2 3]
print(array_3D[0][1]) #[4 5 6]
print(array_3D[1][0]) #[7 8 9]
print(array_3D[1][1]) #[10 11 12]
print(array_3D[0][0][0]) #1
print(array_3D[1,1,2]) #12
```

In [4]:
# CÓDIGO DE LA SECCIÓN 1.3 ÍNDICES de los Arrays
print(f'\n{"="*15} 1.3 ÍNDICES de los Arrays')

# Creación de una lista 2D
print("\n1.3.1 Array de 2 dimensiones y sus índices:")
lista_2D = [[1,2,3,4,5],  [6,7,8,9,10]]
array_2D = np.array(lista_2D)
print(array_2D)
array_2D_bis = np.array([[1,2,3,4,5],  [6,7,8,9,10]])
una_tupla = np.array((1,2,3,4,5)) # Conversión de una tupla en array
print(f'{una_tupla} - {type(una_tupla)}') # [1 2 3 4 5] - <class 'numpy.ndarray'>

# 1.3.1 Array 2 dimensiones
print(f'{array_2D[1][3],array_2D[0][3]}')# 9 y # 4 
print(array_2D[1,4]) # 10 primer numero es el array, segundo la posición
print(f'{array_2D[1][3] + array_2D[0][3]}') # SUMA y sale 13
print(f'{type(array_2D[1][3]),array_2D[0][3]}') #Type da (<class 'numpy.int64'>, np.int64(4))

#1.3.2 Array 3 dimensiones
print("\n1.3.2 Array de 3 dimensiones y sus índices:")
array_2d_otro = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(array_2d_otro.ndim)
array_3D = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])
print(array_3D[0]) #[[1 2 3]
 #[4 5 6]]
print(array_3D[0][0]) #[1 2 3]
print(array_3D[0][1]) #[4 5 6]
print(array_3D[1][0]) #[7 8 9]
print(array_3D[1][1]) #[10 11 12]
print(array_3D[0][0][0]) #1
print(array_3D[1,1,2]) #12


=============== 1.3 ÍNDICES de los Arrays

1.3.1 Array de 2 dimensiones y sus índices:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[1 2 3 4 5] - <class 'numpy.ndarray'>
(np.int64(9), np.int64(4))
10
13
(<class 'numpy.int64'>, np.int64(4))

1.3.2 Array de 3 dimensiones y sus índices:
2
[[1 2 3]
 [4 5 6]]
[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]
1
12


# 1.4 RANGOS  

**arange() y linespace() DEVUELVEN UN ARRAY

### 1.4.1 Método arange() 

`np.arange(inicio, fin no incluido, paso/step)`

### 1.4.1 Método linespace() 

`np.linspace(inicio, fin no incluido, punto equidistante entre inicio y fin)`

In [5]:
# CÓDIGO DE LA SECCIÓN 1.4 RANGOS
print("="*15+"1.4 RANGOS")

# DEVUELVEN ARRAYS
print("ARANGE y LINSPACE devuelven ARRAYS")

print("\n1.4.1 Método arange()")
rango = np.arange(1,20,2) #inicio 1, hasta 19, salto 2
print(rango) #[ 1  3  5  7  9 11 13 15 17 19]
rango #array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

print("\n1.4.2 Método linespace()")
linspace = np.linspace(1,10,3) # calcula solo la equidistancia
print(linspace) #[ 1.   5.5 10. ] 
linspace #array([ 1. ,  5.5, 10. ])





===============1.4 RANGOS
ARANGE y LINSPACE devuelven ARRAYS

1.4.1 Método arange()
[ 1  3  5  7  9 11 13 15 17 19]

1.4.2 Método linespace()
[ 1.   5.5 10. ]


array([ 1. ,  5.5, 10. ])

# 1.5 NÚMEROS ALEATORIOS

### 1.5.1 CREAR UN GENERADOR (objeto)

Se crea un objeto con el método **np.random.default_rng()**  

```
rng = np.random.default_rng()
print(rng) #Imprime Generator(PCG64)
```

Este objeto tiene sus métodos:  
    - uniform()  
    - integers()  
    - choice()  
    - normal()  

```
rng = np.random.default_rng()
rng.uniform(low= , high= , size= )
rng.choice(a=  ,size= , replace= True)

```
** A) PARÁMETRO SIZE**
El parámetro size: forma (shape) del resultado.  
    - si size es None → devuelve un solo valor
    - si size es un entero → devuelve un array 1D
    - si size es una tupla → devuelve un array multidimensional

** B) PARÁMETRO replace EN CHOICE()**

replace=True (por defecto) **un mismo valor puede salir varias veces**

`rng.choice([1, 2, 3], size=5, replace=True) # [1 3 3 1 3 1 1 2 2 1]`

`print(rng.choice([1, 2, 3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20], size=10, replace=False)) # [ 4 16  9  2 19 12  3  5 17  6]`

*Ménos números que el valor de size, con replace=False, da error*

### 1.5.2 PONER UNA SEMILLA default_rng(SEMILLA)

Para qué sirve fijar la semilla: siempre producirá la misma salida, en cualquier ordenador.

```
rng = np.random.default_rng(42)
print(rng.integers(0, 10, 5))
```


In [6]:
# CÓDIGO DE LA SECCIÓN 1.5 NÚMEROS ALEATORIOS

print("="*15+"1.5 NÚMEROS ALEATORIOS")

print("\n1.5.1 Números aleatorios con random.default_rng() SIN SEMILLA FIJA")
rng = np.random.default_rng()
print(rng) #Imprime Generator(PCG64)

print("random.default_rng = distintos números aleatorios cada vez")


print("--- Método integers() ---")
for i in range(5):
    print(rng.integers(low=1, high=10, size=1)) # número aleatorio entero entre 1 y 9
print("--- Método random() ---")
for i in range(5):
    print(rng.random(size=1)) # número aleatorio float entre 0 y 1
print("--- Método uniform() ---")
for i in range(5):
    print(rng.uniform(low=1.0, high=10.0, size=1)) # número aleatorio float entre 1 y 10
print("--- Método normal() ---")
for i in range(5):
    print(rng.normal(loc=0.0, scale=1.0, size=1)) # número aleatorio float con distribución normal
print("--- Método choice() ---")
for i in range(5):
    print(rng.choice([10,20,30,40,50], size=1)) # número aleatorio elegido entre los de la lista


print("\n1.5.2 Números aleatorios con random.default_rng() CON SEMILLA FIJA")
rng = np.random.default_rng(42) # Hace que la semilla sea la misma
print(rng) #Imprime Generator(PCG64)

print("SE REPITEN LOS MISMOS MÉTODOS QUE EN EL PUNTO 1.5.1 PERO CON SEMILLA FIJA")

print("random.default_rng = distintos números aleatorios cada vez")
print("--- Método integers() ---")
for i in range(5):
    print(rng.integers(low=1, high=10, size=1)) # número aleatorio entero entre 1 y 9
print("--- Método random() ---")
for i in range(5):
    print(rng.random(size=1)) # número aleatorio float entre 0 y 1
print("--- Método uniform() ---")
for i in range(5):
    print(rng.uniform(low=1.0, high=10.0, size=1)) # número aleatorio float entre 1 y 10
print("--- Método normal() ---")
for i in range(5):
    print(rng.normal(loc=0.0, scale=1.0, size=1)) # número aleatorio float con distribución normal
print("--- Método choice() ---")
for i in range(5):
    print(rng.choice([10,20,30,40,50], size=1)) # número aleatorio elegido entre los de la lista

print("\n1.5.3 Números aleatorios SIN GENERADOR default_rng()")
aleatorio_normal = np.random.rand(1,100)
print("\nrandom.rand = aleatorios normales - Se empieza por 1 y no por 0")
print("\nrandom.rand(CUANTOS, COMO UN BUCLE) = SOLO UNA DIMENSION")
aleatorio_una_dimension = pd.Series(np.random.rand(4)) # 4 números
print(aleatorio_una_dimension)
print("OJO: ESTO DE ARRIBA ES UNA SERIE DE PANDAS, NO UN ARRAY DE NUMPY")


print("\n=== SEGUIMOS random.rand = aleatorios normales - Se empieza por 1 y no por 0")
print("\n--- Bucles de 5 vueltas ---")
print("\n--- np.random.rand = ARRAY (20 NÚMEROS) ---")
for i in range(5): # PRIMER NÚMERO DEBE SER EL 1 Y NO EL 0
    print(np.random.rand(1,20)) # así saca una array con 20 números float entre 0 y 1

print("\n--- np.random.randint = un ENTERO")
for i in range(5): # PRIMER NÚMERO DEBE SER EL 1 Y NO EL 0
    print(np.random.randint(1,100)) # Sólo saca UN ENTERO entre 1 y 100
    # DEPRECADO print(np.random.random_integers(1,100,10)) # DEPRECATED: Devuelve un array de enteros

print("\nOTRO ALEATORIO: con parámetros np.random.randint(low=0, high=10, size=50) ==> 0 INCLUIDO - 10 EXCLUIDO SIZE=CUANTOS")
print(np.random.randint(low=0, high=10, size=50)) #0 INCLUIDO - 10 EXCLUIDO SIZE=CUANTOS # Imprime el array



===============1.5 NÚMEROS ALEATORIOS

1.5.1 Números aleatorios con random.default_rng() SIN SEMILLA FIJA
Generator(PCG64)
random.default_rng = distintos números aleatorios cada vez
--- Método integers() ---
[6]
[1]
[2]
[8]
[9]
--- Método random() ---
[0.85885819]
[0.80690635]
[0.29350706]
[0.04751208]
[0.29745663]
--- Método uniform() ---
[5.80851075]
[4.34048674]
[7.66793775]
[2.20087748]
[3.73551956]
--- Método normal() ---
[-2.01748897]
[1.25713456]
[0.43320396]
[-0.58907494]
[-0.42576152]
--- Método choice() ---
[40]
[50]
[50]
[30]
[20]

1.5.2 Números aleatorios con random.default_rng() CON SEMILLA FIJA
Generator(PCG64)
SE REPITEN LOS MISMOS MÉTODOS QUE EN EL PUNTO 1.5.1 PERO CON SEMILLA FIJA
random.default_rng = distintos números aleatorios cada vez
--- Método integers() ---
[1]
[7]
[6]
[4]
[4]
--- Método random() ---
[0.69736803]
[0.09417735]
[0.97562235]
[0.7611397]
[0.78606431]
--- Método uniform() ---
[2.15302269]
[5.05347344]
[4.33718222]
[9.3408849]
[6.79478608]
--- Método 

# 1.6 Buscar y modificar elementos de un Array

*Para buscar elementos en un array* **no usar un bucle for**


### 1.6.1 Búsqueda: SE UTILIZA EL MÉTODO **where()**

El método where() devuelve un array con las posiciones donde se encuentra el valor buscado

```
array = [1,2,3,4]
array_resultado = np.where(array==valor_a_buscar)
print(array_resultado) # (array([3]),)
```


### 1.6.2 Cambio de un valor

Síntaxis de la búsqueda y cambio en una línea: donde encuentra un 4 lo cambia a 0
```
array = [1,2,3,4]
array[array == 4] = 0 
print(array) # [1 2 3 0]
```

In [7]:
# CÓDIGO DE LA SECCIÓN 1.6 NÚMEROS ALEATORIOS

print("="*15+"1.6 Buscar y modificar elementos de un Array")

# NO USAR BUCLES PARA RECORRER LOS ARRAYS DE NUMPY
print("\nNO USAR BUCLES PARA RECORRER LOS ARRAYS DE NUMPY")
array_cambiar = np.array([1,2,4,34,4,32,2], dtype=int)
mensaje = ""
for indice,elemento in enumerate(array_cambiar): 
    if (elemento == 4):
        mensaje += f'¡¡¡Encontré el {elemento} en la posición {indice} Y LO CAMBIÉ A 0!!!\n'
    else:
        mensaje += f'Encontré el {elemento} en la posición {indice}\n'
print(mensaje) 

#1.6.1 Buscar elementos de un Array con .where()
print("\n1.6.1 Buscar elementos de un Array con .where()")
print(f"Array original: {array_cambiar}")
print("Buscamos el número 4")
array_cambiar = np.array([1,2,4,34,4,32,2], dtype=int)
# Se busca en un array con .where
array_busqueda = np.where(array_cambiar == 4)
#array_busca devuelve una tupla con un array de índices
# (array([2, 4]),)
print(f'Resultado de la búsqueda: {array_busqueda}') # (array([2, 4]),) # aparece en las posiciones 2 y 4


#1.6.2 Modificar elementos de un Array 
print("\n1.6.2 Modificar elementos de un Array (4 a 0)")
array_cambiar = np.array([1,2,4,34,4,32,2], dtype=int)
array_cambiar[array_cambiar == 4] = 0
print(f"Array modificado: {array_cambiar}")


===============1.6 Buscar y modificar elementos de un Array

NO USAR BUCLES PARA RECORRER LOS ARRAYS DE NUMPY
Encontré el 1 en la posición 0
Encontré el 2 en la posición 1
¡¡¡Encontré el 4 en la posición 2 Y LO CAMBIÉ A 0!!!
Encontré el 34 en la posición 3
¡¡¡Encontré el 4 en la posición 4 Y LO CAMBIÉ A 0!!!
Encontré el 32 en la posición 5
Encontré el 2 en la posición 6


1.6.1 Buscar elementos de un Array con .where()
Array original: [ 1  2  4 34  4 32  2]
Buscamos el número 4
Resultado de la búsqueda: (array([2, 4]),)

1.6.2 Modificar elementos de un Array (4 a 0)
Array modificado: [ 1  2  0 34  0 32  2]


# 1.7 OTROS SUPUESTOS: strings

In [8]:
# CÓDIGO DE LA SECCIÓN 1.7 OTROS SUPUESTOS: strings

print("="*15+"1.7 OTROS SUPUESTOS: strings")

# Conversión de una lista 1D

lista_nombres1 = ["Pepito", "Luisito", "Manolito"]
array_nombres1 = np.array(lista_nombres1)
print(type(array_nombres1)) #'numpy.ndarray'
print(array_nombres1)
print(f'Número de dimensiones array_nombres1: {array_nombres1.ndim}') #1
print("Se crea otro con varias dimensiones")
array_nombres2 = np.array(["Pepito", "Luisito", "Manolito"], ndmin=4)
print(array_nombres2) # [[[['Pepito' 'Luisito' 'Manolito']]]]
print(f'Número de dimensiones array_nombres2: {array_nombres2.ndim}') #4
#ndmin = dimensiones y las crea, aunque esté vacío y se mete como parámetro en np.array(lista,ndmin=4)
#narray.ndim imprime el número de dimensiones




===============1.7 OTROS SUPUESTOS: strings
<class 'numpy.ndarray'>
['Pepito' 'Luisito' 'Manolito']
Número de dimensiones array_nombres1: 1
Se crea otro con varias dimensiones
[[[['Pepito' 'Luisito' 'Manolito']]]]
Número de dimensiones array_nombres2: 4
