# 01 - NumPy

In [8]:
import numpy as np
import pandas as pd
import os
import sys
from IPython.display import display

print("="*15+" NUMPY VERSIÓN")
print("Instrucción en un print: np.__version__")
print(np.__version__) # imprime versión de numpy (sólo números)

=============== NUMPY VERSIÓN
Instrucción en un print: np.__version__
2.4.1


# 1.1 ARRAYS Y SUS DIMENSIONES

### 1.1.1 *Método* **.array()** 

`np.array(lista)`: 
- Crea un array a partir de la lista o tupla.
- El array creado es del tipo **ndarray**
- Los elementos de la lista o tupla han de ser TODOS DEL MISMO TIPO
- La función devuelve una referencia a él.


### 1.1.2 Dimensiones de un array
- El número de dimensiones de un array dependerá de las listas o tuplas anidadas en lista que se convierte.
* **VECTOR**: Para una lista de valores se crea un array de una dimensión.
* **MATRIZ**: Para una lista de listas de valores se crea un array de dos dimensiones.

`np.array(lista, otros parámetros como ndmin=número máximo de columnas)`


### 1.1.3 PROPIEDADES de un array
**ndim** = numero de dimensiones  
**dtype** = tipo de datos a lo que ha convertido numpy el array *(Strings: U8 Unicode con la longitud del más largo)*  
**shape** = devuelve una tupla con las (filas, columnas) del array


### 1.1.4 **INTERPRETACIÓN DE LAS DIMENSIONES (sobre todo a partir de la 3º dimensión)**
np.array([[2],[2]],ndmin=3) *ndim=3 añade la tercera dimensión*

**A) ARRAY SIN EL PARÁMETRO ndim=3**
El contenido sería:
[[2],
 [2]]

*Interpretación:* es un array 2D con forma (2, 1)
    2 filas
    1 columna

**A) ARRAY con EL PARÁMETRO ndim=3** 
ndmin=3 NO añade datos, añade EJES de tamaño 1 por delante hasta llegar a **3 DIMENSIONES**.

**A.1 - Primer ejemplo**
```
    [[[2]
[2]]]
```
No son filas ni columnas, **son EJES**. *“el array tiene 3 ejes, y en cada eje hay cierto número de elementos”*
**SHAPE = (1,2,1)**  
Axis--------Tamaño  
axis 0------1  [primer eje] --> en este eje hay 1 elemento que es el número [-----[[2][2]]-----]  
axis 1------2  [segundo eje] --> en este eje hay 2 elementos que son los números 2 y 2 [-----[2][2]-----]  
axis 2------1 [tercer eje]-- > en este eje hay 1 elemento que es el número 2 [2]  

**A.2 - Segundo ejemplo**
```
    [[[2,2]
[2,2]]]
```

**REPETIMOS:** No son filas ni columnas, **son EJES**. *“el array tiene 3 ejes, y en cada eje hay cierto número de elementos”*  
**SHAPE = (1,2,2)**  
Axis--------Tamaño  
axis 0------1  [primer eje] --> en este eje hay 1 elemento que es el número [-----[[2,2][2,2]]-----]  
axis 1------2  [segundo eje] --> en este eje hay 2 elementos que son los números 2 y 2 [-----[2,2][2,2]-----]  
axis 2------1 [tercer eje]-- > en este eje hay 2 elementos que son el número 2 [2,2]  

In [ ]:
# CÓDIGO DE LA SECCIÓN 1.1 ARRAYS Y SUS DIMENSIONES

# 1.1.1 MÉTODO .ARRAY()
print("="*15+" 1.1.1 MÉTODO ARRAY()")
lista = [1,2,4,34,4,32,2]
tupla = (1,2,4,34,4,32,2)

# Crear un array a partir de la lista

print("Array de la lista")
array_de_lista = np.array(lista) # Método array() crea un ndarray
print(array_de_lista) # [ 1  2  4 34  4 32  2]
print(type(array_de_lista)) #ndarray 

array_de_tupla = np.array(tupla)
print("Array de la tupla")
print(array_de_tupla) # [ 1  2  4 34  4 32  2]
print(type(array_de_tupla)) #ndarray

# 1.1.2 DIMENSIONES de un array
print(f'\n{"="*15} 1.1.2 DIMENSIONES: VECTOR Y MATRIZ')
# A) VECTOR: 1 dimensión
vector = np.array([1,2,3,4,5])
print(f'A) Vector o array unidimensional: {vector}') # Array unidimensional: [1 2 3 4 5]

# B) MATRIZ: 2 dimensiones
matriz = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f'B) Matriz o array bidimensional (matriz):\n{matriz}')
#[[1 2 3]
#[4 5 6]
#[7 8 9]]


# 1.1.3 PROPIEDADES de un array
print(f'\n{"="*15} 1.1.3 PROPIEDADES de un array')
# A) PROPIEDAD NDIM
print(f'A) PROPIEDAD NDIM')
print(f'Numero de dimensiones del array de la lista: {array_de_lista.ndim}') # Número de dimensiones: 1
print(f'Número de dimensiones del vector: {vector.ndim}') # Número de dimensiones: 1
print(f'Número de dimensiones de la matriz: {matriz.ndim}') # Número de dimensiones: 2

# B) PROPIEDAD SHAPE
print(f'\nB) PROPIEDAD SHAPE')
print(f'Shape del array_de_lista: {array_de_lista.shape}') # Shape del array: (7,)
# 7 elementos, sin una estructura de filas/columnas
print("array_de_lista: 7 elementos, sin una estructura de filas/columnas")
print(f'Shape del vector: {vector.shape}') # Shape del vector: (5,)
print("Vector: 5 elementos, sin una estructura de filas/columnas")
print(f'Shape de la matriz: {matriz.shape}') # Shape de la matriz: (3, 3)
print("matriz: 3 filas y 3 columnas (FILAS, COLUMNAS)")

# C) PROPIEDAD DTYPE
#dtype = tipo de datos tal como los ha convertido NumPy dentro del array U8 Unicode con la longitud del más largo
print(f'\nC) PROPIEDAD DTYPE')
array_con_strings = np.array(["Pepe","Luis","Ana","Federico","María"])
print(f'Dtype del array_con_strings: {array_con_strings.dtype}') # Dtype del array_con_strings: <U8  (U8 = Unicode con longitud máxima 8)
# Los arrays deben ser HOMOGÉNEOS, es decir, todos los elementos del array deben ser del mismo tipo de dato
# Si se mezclan tipos de datos, NumPy convierte todos los elementos al tipo de dato que pueda contener a todos los elementos
array_mezclado_strings = np.array([["Pepe","Luis","Ana","Federico","María"],[1,2,3,4,5]],ndmin=2)
print(f'Shape del array_mezclado_strings: {array_mezclado_strings.shape}') #(2,5)
#TODAS LAS COLUMNAS TIENEN QUE TENER EL MISMO NÚMERO DE ELEMENTOS, SI NO, PON '' EN LAS QUE FALTEN
print(f'Dtype del array_mezclado_strings: {array_mezclado_strings.dtype}') # Dtype del array_mezclado_strings: <U21 


# 1.1.4 INTERPRETACIÓN DE LAS DIMENSIONES (sobre todo a partir de la 3º dimensión)
#ndmin = número mínimo de dimensiones que tendrá el array creado
print(f'\n{"="*15} 1.1.4 INTERPRETACIÓN DE LAS DIMENSIONES (sobre todo a partir de la 3º dimensión)')

array_de_3_dimensiones_a = np.array([[2],[2]],ndmin=3)
print(f'\nEjemplo primero: Array con 3 dimensiones a: {array_de_3_dimensiones_a}') 
# [[[2]
#  [2]]]

print(f'Shape del array_de_3_dimensiones_a: {array_de_3_dimensiones_a.shape}') #(1,2,1)
#No son filas ni columnas, **son EJES**. *“el array tiene 3 ejes, y en cada eje hay cierto número de elementos”*  
#Axis--------Tamaño  
#axis 0------1  [primer eje] --> en este eje hay 1 elemento que es el número [-----[[2][2]]-----]
#axis 1------2  [segundo eje] --> en este eje hay 2 elementos que son los números 2 y 2 [-----[2][2]-----]
#axis 2------1 [tercer eje]-- > en este eje hay 1 elemento que es el número 2 [2]

print("\nOtro ejemplo: el array anterior con 3 dimensiones pero con más elementos")
array_de_3_dimensiones_b = np.array([[2,2],[2,2]],ndmin=3)
print(f'\nArray con 3 dimensiones b: {array_de_3_dimensiones_b}') 
# [[[2,2]
#  [2,2]]]

print(f'Shape del array_de_3_dimensiones_b: {array_de_3_dimensiones_b.shape}') #(1,2,2)
#No son filas ni columnas, **son EJES**. *“el array tiene 3 ejes, y en cada eje hay cierto número de elementos”*  
#Axis--------Tamaño  
#axis 0------1  [primer eje] --> en este eje hay 1 elemento que es el número [-----[[2,2][2,2]]-----]
#axis 1------2  [segundo eje] --> en este eje hay 2 elementos que son los números 2 y 2 [-----[2,2][2,2]-----]
#axis 2------1 [tercer eje]-- > en este eje hay 2 elementos que son el número 2 [2,2]

# OTRO EJEMPLO: un arrayGigante con 10 dimensiones
arrayGigante = np.array([1,2,3],ndmin=10)
print("\nArray Gigante con 10 dimensiones:")
print(arrayGigante) # [[[[[[[[[[1 2 3]]]]]]]]]]
print(f'SHAPE del arrayGigante: {arrayGigante.shape}') # (1, 1, 1, 1, 1, 1, 1, 1, 1, 3)


=============== 1.1.1 MÉTODO ARRAY()
Array de la lista
[ 1  2  4 34  4 32  2]
<class 'numpy.ndarray'>
Array de la tupla
[ 1  2  4 34  4 32  2]
<class 'numpy.ndarray'>

=============== 1.1.2 DIMENSIONES: VECTOR Y MATRIZ
A) Vector o array unidimensional: [1 2 3 4 5]
B) Matriz o array bidimensional (matriz):
[[1 2 3]
 [4 5 6]
 [7 8 9]]

=============== 1.1.3 PROPIEDADES de un array
A) PROPIEDAD NDIM
Numero de dimensiones del array de la lista: 1
Número de dimensiones del vector: 1
Número de dimensiones de la matriz: 2

B) PROPIEDAD SHAPE
Shape del array_de_lista: (7,)
array_de_lista: 7 elementos, sin una estructura de filas/columnas
Shape del vector: (5,)
Vector: 5 elementos, sin una estructura de filas/columnas
Shape de la matriz: (3, 3)
matriz: 3 filas y 3 columnas (FILAS, COLUMNAS)

C) PROPIEDAD DTYPE
Dtype del array_con_strings: <U8
Shape del array_mezclado_strings: (2, 5)
Dtype del array_mezclado_strings: <U21

=============== 1.1.4 Crear arrays con un número mínimo de dimensiones

E

# 1.2 ÍNDICES

In [ ]:
# FIN DEL CÓDIGO DE LA SECCIÓN 1.1 ARRAYS Y SUS DIMENSIONES
#INDICES
# Otro ejemplo de búsqueda 
# Conversión de una lista 2D
lista_2D = [[1,2,3,4,5],  [6,7,8,9,10]]
array_2D = np.array(lista_2D)
print(array_2D)
array_2D_bis = np.array([[1,2,3,4,5],  [6,7,8,9,10]])
una_tupla = np.array((1,2,3,4,5))
print(f'{una_tupla} - {type(una_tupla)}') 

# Por índices
print(f'{array_2D[1][3],array_2D[0][3]}')# 9 y # 4 abajo es igual
print(array_2D_bis[1,4]) # 10 primer numero es el array, segundo la posición
print(f'{array_2D[1][3] + array_2D[0][3]}') # SUMA y sale 13
print(f'{type(array_2D[1][3]),array_2D[0][3]}') #Type da int

# 1.3 RANGOS  
np.arrange(inicio, fin no incluido, paso/step)  
np.linspace(inicio, fin no incluido, punto equidistante entre inicio y fin)

In [ ]:
# CÓDIGO DE LA SECCIÓN 1.3 RANGOS
print("="*15+"RANGOS")

# DEVUELVEN ARRAYS
print("Devuelven arrays: ")
rango1 = np.arange(1,20,2) #inicio 1, hasta 19, salto 2
print(rango1) #[ 1  3  5  7  9 11 13 15 17 19]
rango1 #array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

linspace1 = np.linspace(1,10,3) # calcula solo la equidistancia
linspace1

print("="*15+"RANGOS E ÍNDICES")

# DEVUELVEN ARRAYS
print("Devuelven arrays: ")
rango1 = np.arange(1,20,2) #inicio 1, hasta 19, salto 2
print(rango1) #[ 1  3  5  7  9 11 13 15 17 19]
rango1 #array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

linspace1 = np.linspace(1,10,3) # calcula solo la equidistancia
linspace1



===============RANGOS
Devuelven arrays: 
[ 1  3  5  7  9 11 13 15 17 19]
===============RANGOS E ÍNDICES
Devuelven arrays: 
[ 1  3  5  7  9 11 13 15 17 19]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[1 2 3 4 5] - <class 'numpy.ndarray'>
(np.int64(9), np.int64(4))
10
13
(<class 'numpy.int64'>, np.int64(4))


# 1.3 NÚMEROS ALEATORIOS
```
np.random.TERCER ELEMENTO()

rand
randint(inicio,fin)


default_rng:
aleatorio_semilla_fija = np.random.default_rng(42) # Hace que la semilla sea la misma
```

In [11]:
# CÓDIGO DE LA SECCIÓN 1.3 NÚMEROS ALEATORIOS
print("="*15+"NÚMEROS ALEATORIOS")
aleatorio_semilla_fija = np.random.default_rng(42) # Hace que la semilla sea la misma
print(aleatorio_semilla_fija) #Imprime Generator(PCG64)

print("random.default_rng = misma semilla pero distinto número aleatorio")

rango = 3 # para el bucle while de abajo
while rango > 0:
    array_numero_aleatorio = aleatorio_semilla_fija.random() # No por ser la misma semilla, el número será el mismo
    print(f'{array_numero_aleatorio} = misma semilla pero distinto número aleatorio')
    rango -= 1

# Aleatorio normal
aleatorio_normal = np.random.rand(1,100)
print("\nrandom.rand = aleatorios normales - Se empieza por 1 y no por 0")
print("\nrandom.rand(CUANTOS, COMO UN BUCLE) = SOLO UNA DIMENSION")
aleatorio_una_dimension = pd.Series(np.random.rand(4)) # 4 números
print(aleatorio_una_dimension)

print("\n=== SEGUIMOS random.rand = aleatorios normales - Se empieza por 1 y no por 0")
rango = 3 # para el bucle while de abajo
while rango > 0: # PRIMER NÚMERO DEBE SER EL 1 Y NO EL 0
    print(np.random.rand(1,20)) # así saca una array con 20 números float entre 0 y 1
    print(np.random.randint(1,100)) # Sólo saca UN ENTERO entre 1 y 100
    print(np.random.random_integers(1,100,10)) # DEPRECATED: Devuelve un array de enteros
    # print(aleatorio_normal) # array 100 números
    rango -=1

print("\nOTRO ALEATORIO: con parámetros np.random.randint(low=0, high=10, size=50) ==> 0 INCLUIDO - 10 EXCLUIDO SIZE=CUANTOS")
otro_aleatorio_normal = np.random.randint(low=0, high=10, size=50) #0 INCLUIDO - 10 EXCLUIDO SIZE=CUANTOS
otro_aleatorio_normal # imprime el array


===============NÚMEROS ALEATORIOS
Generator(PCG64)
random.default_rng = misma semilla pero distinto número aleatorio
0.7739560485559633 = misma semilla pero distinto número aleatorio
0.4388784397520523 = misma semilla pero distinto número aleatorio
0.8585979199113825 = misma semilla pero distinto número aleatorio

random.rand = aleatorios normales - Se empieza por 1 y no por 0

random.rand(CUANTOS, COMO UN BUCLE) = SOLO UNA DIMENSION
0    0.336332
1    0.530143
2    0.857666
3    0.833780
dtype: float64

=== SEGUIMOS random.rand = aleatorios normales - Se empieza por 1 y no por 0
[[0.15348924 0.74401152 0.60702416 0.58952238 0.31902051 0.29940309
  0.27493428 0.94292929 0.73708074 0.7380862  0.54388958 0.35482417
  0.8652128  0.95672911 0.2535069  0.32150114 0.21257318 0.26124983
  0.76970693 0.00397922]]
64
[41 49 50 56 37 31 31 75 74 12]
[[0.2307876  0.13793456 0.19449297 0.92912497 0.64410019 0.60511814
  0.70170431 0.65317499 0.88878978 0.7268341  0.17803091 0.21302767
  0.62936236

C:\Users\angel\AppData\Local\Temp\ipykernel_38272\4154913826.py:26: DeprecationWarning: This function is deprecated. Please call randint(1, 100 + 1) instead
  print(np.random.random_integers(1,100,10)) # DEPRECATED: Devuelve un array de enteros


array([6, 6, 8, 6, 1, 9, 7, 4, 5, 9, 8, 4, 5, 1, 0, 1, 7, 4, 9, 3, 6, 2,
       3, 2, 1, 4, 9, 8, 5, 7, 3, 6, 3, 3, 5, 1, 7, 6, 3, 9, 1, 5, 7, 0,
       7, 8, 9, 6, 9, 9], dtype=int32)

# 1.4 Buscar y modificar elementos de un Array

no usar bucle for

array1 = [1,2,3,4]
SINTAXIS BÚSQUEDA
elementos = np.where(array1 == 4)

SINTAXIS CAMBIO
array1[array1 == 4] = 0

In [12]:


# NO USAR BUCLES PARA RECORRER UN ARRAY DE NUMPY
array_cambiar = np.array([1,2,4,34,4,32,2], dtype=int)
mensaje = ""
for indice,elemento in enumerate(array_cambiar): 
    if (elemento == 4):
        mensaje += f'¡¡¡Encontré el {elemento} en la posición {indice} Y LO CAMBIÉ A 0!!!\n'
    else:
        mensaje += f'Encontré el {elemento} en la posición {indice}\n'
print(mensaje) 

# Se busca en un array con .where
array_busca = np.where(array_cambiar == 4)
#array_busca devuelve una tupla con un array de índices
# (array([2, 4]),)
print(array_busca) # (array([2, 4]),) # aparece en las posiciones 2 y 4
#for i in array_busca:
    # i = 0 ESTO DA ERROR Y NI BUSCA NI HACE NADA
# se modifica el array más fácil y correctamente con NumPy de este modo
array_cambiar[array_cambiar == 4] = 0
array_cambiar


Encontré el 1 en la posición 0
Encontré el 2 en la posición 1
¡¡¡Encontré el 4 en la posición 2 Y LO CAMBIÉ A 0!!!
Encontré el 34 en la posición 3
¡¡¡Encontré el 4 en la posición 4 Y LO CAMBIÉ A 0!!!
Encontré el 32 en la posición 5
Encontré el 2 en la posición 6

(array([2, 4]),)


array([ 1,  2,  0, 34,  0, 32,  2])

# 1.1.5 OTROS SUPUESTOS

In [13]:
# OTROS EJEMPLOS DE ARRAYS

# Conversión de una lista 1D

lista_nombres1 = ["Pepito", "Luisito", "Manolito"]
array_nombres1 = np.array(lista_nombres1)
print(type(array_nombres1)) #'numpy.ndarray'
print(array_nombres1)
print(f'Número de dimensiones array_nombres1: {array_nombres1.ndim}') #1
print("Se crea otro con varias dimensiones")
array_nombres2 = np.array(["Pepito", "Luisito", "Manolito"], ndmin=4)
print(array_nombres2) # [[[['Pepito' 'Luisito' 'Manolito']]]]
print(f'Número de dimensiones array_nombres2: {array_nombres2.ndim}') #4
#ndmin = dimensiones y las crea, aunque esté vacío y se mete como parámetro en np.array(lista,ndmin=4)
#narray.ndim imprime el número de dimensiones




<class 'numpy.ndarray'>
['Pepito' 'Luisito' 'Manolito']
Número de dimensiones array_nombres1: 1
Se crea otro con varias dimensiones
[[[['Pepito' 'Luisito' 'Manolito']]]]
Número de dimensiones array_nombres2: 4
