# 01 - NumPy

In [5]:
import numpy as np
import pandas as pd
import os
import sys
from IPython.display import display

print("="*15+" NUMPY VERSIÓN")
print("Instrucción en un print: np.__version__")
print(np.__version__) # imprime versión de numpy (sólo números)

=============== NUMPY VERSIÓN
Instrucción en un print: np.__version__
2.4.1


# Numeros aleatorios
```
np.random.TERCER ELEMENTO()

rand
randint(inicio,fin)


default_rng:
aleatorio_semilla_fija = np.random.default_rng(42) # Hace que la semilla sea la misma
```

In [ ]:
os.system('cls')
print("="*15+"ALEATORIOS")
aleatorio_semilla_fija = np.random.default_rng(42) # Hace que la semilla sea la misma
print(aleatorio_semilla_fija) #Imprime Generator(PCG64)

print("random.default_rng = misma semilla pero distinto número aleatorio")

rango = 3 # para el bucle while de abajo
while rango > 0:
    array_numero_aleatorio = aleatorio_semilla_fija.random() # No por ser la misma semilla, el número será el mismo
    print(f'{array_numero_aleatorio} = misma semilla pero distinto número aleatorio')
    rango -= 1

# Aleatorio normal
aleatorio_normal = np.random.rand(1,100)
print("\nrandom.rand = aleatorios normales - Se empieza por 1 y no por 0")
print("\nrandom.rand(CUANTOS, COMO UN BUCLE) = SOLO UNA DIMENSION")
aleatorio_una_dimension = pd.Series(np.random.rand(4)) # 4 números
print(aleatorio_una_dimension)

print("\n=== SEGUIMOS random.rand = aleatorios normales - Se empieza por 1 y no por 0")
rango = 3 # para el bucle while de abajo
while rango > 0: # PRIMER NÚMERO DEBE SER EL 1 Y NO EL 0
    print(np.random.rand(1,20)) # así saca una array con 20 números float entre 0 y 1
    print(np.random.randint(1,100)) # Sólo saca UN ENTERO entre 1 y 100
    print(np.random.random_integers(1,100,10)) # DEPRECATED: Devuelve un array de enteros
    # print(aleatorio_normal) # array 100 números
    rango -=1

print("\nOTRO ALEATORIO: con parámetros np.random.randint(low=0, high=10, size=50) ==> 0 INCLUIDO - 10 EXCLUIDO SIZE=CUANTOS")
otro_aleatorio_normal = np.random.randint(low=0, high=10, size=50) #0 INCLUIDO - 10 EXCLUIDO SIZE=CUANTOS
otro_aleatorio_normal # imprime el array


===============ALEATORIOS
Generator(PCG64)
random.default_rng = misma semilla pero distinto número aleatorio
0.7739560485559633 = misma semilla pero distinto número aleatorio
0.4388784397520523 = misma semilla pero distinto número aleatorio
0.8585979199113825 = misma semilla pero distinto número aleatorio

random.rand = aleatorios normales - Se empieza por 1 y no por 0

random.rand(4) = SOLO UNA DIMENSION
0    0.007353
1    0.995964
2    0.203253
3    0.831187
dtype: float64

=== SEGUIMOS random.rand = aleatorios normales - Se empieza por 1 y no por 0
[[0.73305881 0.15810593 0.41778771 0.15926479 0.85215777 0.20707868
  0.27774774 0.25782375 0.95081185 0.83290403 0.35288541 0.95566573
  0.58622164 0.4194204  0.05333113 0.84972625 0.14588381 0.52638203
  0.55714873 0.37501038]]
61
[15 31 52 80 41 23 72 21 18 65]
[[0.96592832 0.7230613  0.60673817 0.97113663 0.92157295 0.67038776
  0.47019994 0.29006706 0.32246577 0.63576562 0.19934696 0.09256069
  0.42060949 0.07999683 0.12524495 0.2802

C:\Users\angel\AppData\Local\Temp\ipykernel_20424\877317843.py:26: DeprecationWarning: This function is deprecated. Please call randint(1, 100 + 1) instead
  print(np.random.random_integers(1,100,10)) # DEPRECATED: Devuelve un array de enteros


array([7, 7, 8, 7, 5, 8, 1, 6, 4, 4, 9, 2, 6, 6, 0, 7, 2, 4, 7, 9, 0, 1,
       3, 8, 9, 1, 0, 6, 7, 0, 6, 7, 9, 6, 5, 0, 5, 8, 0, 3, 7, 6, 3, 5,
       2, 4, 2, 9, 5, 1], dtype=int32)

# RANGOS
np.arrange(inicio, fin no incluido, paso/step)
np.linspace(inicio, fin no incluido, punto equidistante entre inicio y fin)

In [68]:
print("="*15+"RANGOS")

# DEVUELVEN ARRAYS
print("Devuelven arrays: ")
rango1 = np.arange(1,20,2) #inicio 1, hasta 19, salto 2
print(rango1) #[ 1  3  5  7  9 11 13 15 17 19]
rango1 #array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

linspace1 = np.linspace(1,10,3) # calcula solo la equidistancia
linspace1

===============RANGOS
Devuelven arrays: 
[ 1  3  5  7  9 11 13 15 17 19]


array([ 1. ,  5.5, 10. ])

# ARRAYS
.array() 

np.array(lista) : Crea un array a partir de la lista o tupla lista IGUALES TIPOS y devuelve una referencia a él. 
El número de dimensiones del array dependerá de las listas o tuplas anidadas en lista:
Para una lista de valores se crea un array de una dimensión, también conocido como vector.
Para una lista de listas de valores se crea un array de dos dimensiones, también conocido como matriz.
np.array(lista, otros parámetros como ndmin=número máximo de columnas)

# PROPIEDADES
ndim = numero de dimensiones 
dtype = tipo de datos a lo que ha convertido numpy el array U8 Unicode con la longitud del más largo
shape = devuelve una tupla con las (filas, columnas) del array


In [ ]:
lista = [1,2,4,34,4,32,2]
array1 = np.array(lista) # Método array() crea un ndarray
print(array1)
print(type(array1)) #ndarray
print(f'Número de dimensiones: {array1.ndim}') # 1
array1.shape # ESTO DEVUELVE UNA TUPLA

arrayGigante = np.array([1,2,3],ndmin=10)
print(arrayGigante) # [[[[[[[[[[1 2 3]]]]]]]]]]
print(arrayGigante.shape) # (1, 1, 1, 1, 1, 1, 1, 1, 1, 3)

#PROPIEDADES
#ndim = numero de dimensiones 
#dtype = tipo de datos tal como los ha convertido NumPy dentro del array U8 Unicode con la longitud del más largo
#shape = devuelve una tupla con las (filas, columnas) del array
# SHAPE del arrayGigante # (1, 1, 1, 1, 1, 1, 1, 1, 1, 3) del ejemplo de arriba


# OTROS EJEMPLOS
array2 = np.array([["a","b","c","d","e"],[1,2,3,4,5]],ndmin=2)
print(array2.shape) #(2,5)
#LAS COLUMNAS TIENEN QUE SER TODAS DE 5

array3 = np.array([[2],[2]],ndmin=3)
print(array3.shape) #(1,2,1)

[ 1  2  4 34  4 32  2]
<class 'numpy.ndarray'>
Número de dimensiones: 1
[[[[[[[[[[1 2 3]]]]]]]]]]
(1, 1, 1, 1, 1, 1, 1, 1, 1, 3)
(2, 5)
(1, 2, 1)


In [73]:
# OTROS EJEMPLOS DE ARRAYS

# Conversión de una lista 1D

lista_nombres1 = ["Pepito", "Luisito", "Manolito"]
array_nombres1 = np.array(lista_nombres1)
print(type(array_nombres1)) #'numpy.ndarray'
print(array_nombres1)
print(f'Número de dimensiones array_nombres1: {array_nombres1.ndim}')
print("Se crea otro con varias dimensiones")
array_nombres2 = np.array(["Pepito", "Luisito", "Manolito"], ndmin=4)
print(array_nombres2) # [[[['Pepito' 'Luisito' 'Manolito']]]]
print(f'Número de dimensiones array_nombres2: {array_nombres2.ndim}')
#ndmin = dimensiones y las crea, aunque esté vacío y se mete como parámetro en np.array(lista,ndmin=4)
#narray.ndim imprime el número de dimensiones

# Conversión de una lista 2D
lista_2D = [[1,2,3,4,5],  [6,7,8,9,10]]
array_2D = np.array(lista_2D)
print(array_2D)
array_2D_bis = np.array([[1,2,3,4,5],  [6,7,8,9,10]])
una_tupla = np.array((1,2,3,4,5))
print(f'{una_tupla} - {type(una_tupla)}') 

# Por índices
print(f'{array_2D[1][3],array_2D[0][3]}')# 9 y # 4 abajo es igual
print(array_2D_bis[1,4]) # 10 primer numero es el array, segundo la posición
print(f'{array_2D[1][3] + array_2D[0][3]}') # SUMA y sale 13
print(f'{type(array_2D[1][3]),array_2D[0][3]}') #Type da int

# PROPIEDAD dtype: devuelve el tipo de datos de dentro del array
print("PROPIEDAD: dtype: devuelve el tipo de datos de dentro del array")
print(array_2D.dtype)
print(array_nombres2.dtype) #U8 Unicode 8 dimensión del más largo

<class 'numpy.ndarray'>
['Pepito' 'Luisito' 'Manolito']
Número de dimensiones array_nombres1: 1
Se crea otro con varias dimensiones
[[[['Pepito' 'Luisito' 'Manolito']]]]
Número de dimensiones array_nombres2: 4
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[1 2 3 4 5] - <class 'numpy.ndarray'>
(np.int64(9), np.int64(4))
10
13
(<class 'numpy.int64'>, np.int64(4))
PROPIEDAD: dtype: devuelve el tipo de datos de dentro del array
int64
<U8


# Buscar y modificar elementos de un Array

no usar bucle for

array1 = [1,2,3,4]
SINTAXIS BÚSQUEDA
elementos = np.where(array1 == 4)

SINTAXIS CAMBIO
array1[array1 == 4] = 0

In [83]:


# NO USAR BUCLES PARA RECORRER UN ARRAY DE NUMPY
array_cambiar = np.array([1,2,4,34,4,32,2], dtype=int)
mensaje = ""
for indice,elemento in enumerate(array_cambiar): 
    if (elemento == 4):
        mensaje += f'¡¡¡Encontré el {elemento} en la posición {indice} Y LO CAMBIÉ A 0!!!\n'
    else:
        mensaje += f'Encontré el {elemento} en la posición {indice}\n'
print(mensaje) 

# Se busca en un array con .where
array_busca = np.where(array_cambiar == 4)
#array_busca devuelve una tupla con un array de índices
# (array([2, 4]),)
print(array_busca) # (array([2, 4]),) # aparece en las posiciones 2 y 4
#for i in array_busca:
    # i = 0 ESTO DA ERROR Y NI BUSCA NI HACE NADA
# se modifica el array más fácil y correctamente con NumPy de este modo
array_cambiar[array_cambiar == 4] = 0
array_cambiar

Encontré el 1 en la posición 0
Encontré el 2 en la posición 1
¡¡¡Encontré el 4 en la posición 2 Y LO CAMBIÉ A 0!!!
Encontré el 34 en la posición 3
¡¡¡Encontré el 4 en la posición 4 Y LO CAMBIÉ A 0!!!
Encontré el 32 en la posición 5
Encontré el 2 en la posición 6

(array([2, 4]),)


array([ 1,  2,  0, 34,  0, 32,  2])